service: aws-container-lambda
framework Version: "2"
provider:
  name: aws
  lambdaHashingVersion: 20201221
  ecr:
    images:
      appimage:
        path: ./
functions:
  get_sentiment:
    image:
      name: appimage
