service: my-service
provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
functions:
  get_sentiment:
    image:
      name: appimage
      timeout: 300
      memorySize: 512
      provisionedConcurrency: 3
      reservedConcurrency: 5

