service: my-service
provider:
  name: aws
  timeout: 300
  ecr:
    images:
      appimage:
        path: ./
functions:
  get_sentiment:
    image:
      name: appimage
    timeout: 300
    memorySize: 512
    ephemeralStorageSize: 512
    provisionedConcurrency: 3
    reservedConcurrency: 5
    events:
      - http:
          path: qa # http path
          method: post # http method
